# Generated by Django 5.1 on 2024-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Ur_View',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
    ]
