# Generated by Django 5.1 on 2024-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_rename_author_post_name_rename_text_post_ur_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
